feat(search indexes): adding users-count api call
amplience/dc-management-sdk-js pull request #54
Opened 2020-08-24 13:55 UTC by Benj0s

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [ ] Tests (`npm run test`) for the changes have been added (for bug fixes / features)
- [ ] Docs (`npm run doc`) have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
N/A

## What is the new behaviour?
 - adding index search analytics users-count api call

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2020-08-24 14:26 UTC, simonmudd approved these changes

2020-08-24 14:29 UTC, easen-amp requested changes
You need to export the new classes in the `./src/index.ts`

2020-08-24 14:29 UTC, easen-amp commented on src/lib/model/SearchIndexUsersCount.ts
> + * Class representing top hits  for an Algolia Search Index
copy & paste error

2020-08-25 07:30 UTC, easen-amp approved these changes

2020-08-25 08:08 UTC, c-bibby approved these changes

2020-08-25 12:16 UTC, merged