feat: Feature/cmp 7269 able to fetch children and parents to create hierarchys
amplience/dc-management-sdk-js pull request #60
Opened 2020-10-01 10:34 UTC by dev-warner

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Tests (`npm run test`) for the changes have been added (for bug fixes / features)
- [x] Docs (`npm run doc`) have been reviewed and added / updated if needed (for bug fixes / features)
- [x] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

current behaviour doesn't support, hierarchy requests.

## What is the new behaviour?

- able to fetch children by id
- able to fetch parents by id
- able to fetch children/parents from sub nodes
- able to fetch content link associated with node

## Does this introduce a breaking change?

- [ ] Yes
- [ x ] No

## Other information

- Changed readme badge to github actions.
- Changed eslint rule to support current use of any
- Fixed eslint warnings for unused vars
- Added some typings

2020-10-01 11:47 UTC, easen-amp commented on src/lib/model/HierarchyChildren.ts
> +   *
Missing comment

2020-10-01 11:48 UTC, easen-amp commented on src/lib/model/PublishingStatus.ts
> +export enum ContentItemPublishingStatus {
I think this is missing a comment/doc

2020-10-01 11:49 UTC, easen-amp commented on src/lib/model/HierarchyNode.ts
> +  /**
Most of this comment should be on the `ContentItemPublishingStatus` enum IMHO

2020-10-01 11:59 UTC, easen-amp requested changes

2020-10-01 11:59 UTC, easen-amp commented on .eslintrc.yaml
> +  '@typescript-eslint/explicit-module-boundary-types': 'off'
I feel like we should have this turned on https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md

> Explicit types for function return values and arguments makes it clear to any calling code what is the module boundary's input and output.
>Consider using this rule in place of no-untyped-public-signature which has been deprecated.

I know this is the source of the eslint lint warnings (which should be addresses).

As this is an SDK, we should enforce that all exported methods have a defined return type, using actual types and not `any`.

2020-10-01 12:12 UTC, easen-amp approved these changes

2020-10-05 09:19 UTC, nsmith-amplience commented on src/lib/DynamicContent.ts
> +  public readonly hierarchys = {
typo, should be `hierarchies`

2020-10-05 10:12 UTC, nsmith-amplience approved these changes

2020-10-06 09:42 UTC, simonmudd approved these changes

2020-10-06 09:57 UTC, Benj0s approved these changes

2020-11-16 12:28 UTC, merged