feat: workflow-state support
amplience/dc-management-sdk-js pull request #70
Opened 2020-12-08 08:58 UTC by easen-amp

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Tests (`npm run test`) for the changes have been added (for bug fixes / features)
- [x] Docs (`npm run doc`) have been reviewed and added / updated if needed (for bug fixes / features)
- [x] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?

Missing workflow states

## What is the new behaviour?

- added workflow states support

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

2020-12-08 16:19 UTC, simonmudd approved these changes

2020-12-10 16:10 UTC, rs-amp requested changes
Just one minor doc omission. Looks good otherwise.

2020-12-10 16:10 UTC, rs-amp commented on src/lib/model/WorkflowState.ts
> +    update: (mutation: WorkflowState): Promise<WorkflowState> =>
No documentation here?

2020-12-14 09:41 UTC, Benj0s approved these changes

2020-12-14 16:19 UTC, rs-amp commented on src/lib/model/WorkflowState.ts
> +  public 'color': string;
Missing newline after this

2020-12-14 16:20 UTC, rs-amp requested changes

2020-12-14 16:20 UTC, rs-amp commented on src/lib/model/WorkflowState.ts
> +  public 'color': string;
Also, is (R,B,G) really the order?

2020-12-16 09:20 UTC, c-bibby approved these changes

2020-12-16 14:06 UTC, rs-amp approved these changes

2020-12-16 14:08 UTC, merged